//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ОООТехносервис.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Requestid { get; set; }
        public System.DateTime RequestData { get; set; }
        public int RequestDeviceid { get; set; }
        public int RequestDefectid { get; set; }
        public int RequestClientid { get; set; }
        public string RequestDescription { get; set; }
        public int RequestStatusid { get; set; }
        public int RequestMasterid { get; set; }
        public int RequestTime { get; set; }
        public int RequestPrioryid { get; set; }
        public int RequestPhaseid { get; set; }
        public string RequestComment { get; set; }
    
        public virtual Defect Defect { get; set; }
        public virtual Device Device { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
